# path to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv

# path to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

# Parameters for submitting jobs to cluster via qsub
cluster_json: cluster.json

ref:
  # Select the genome of the organism, needed to perform GO analyses. Supported: mouse, human.
  genome: "mouse"
  # the STAR index
  index: "/hpcnfs/data/DP/Databases/STAR_mm10_v2_7"
  # gtf file with transcripts
  annotation: "/hpcnfs/data/DP/Databases/STAR_mm10_v2_7/gencode.vM19.primary_assembly.annotation.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # Filter thresholds to call differentially expressed genes
  pvalue: 0.05
  log2fc: 3
  # contrasts for the deseq2 results method
  contrasts:
    P1KO-vs-WT:
      - P1KO
      - WT
    P24KO-vs-WT:
      - P24KO
      - WT
    P35KO-vs-WT:
      - P35KO
      - WT
    P6KO-vs-WT:
      - P6KO
      - WT

# Parameters for some of the programs used in the pipeline
params:
  star: "--outSAMattributes Standard \
        --outFilterMultimapNmax 1"
  featureCounts: "-s 0 -t exon -g gene_name"
  fastp-se: "--stdin -t 1 -A -Q -L"
  fastp-pe: "-t 1 -A -Q -L"
