# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

# Parameters for submitting jobs to cluster via qsub
cluster_json: cluster.json

ref:
  # the STAR index
  index: "/hpcnfs/data/DP/Databases/STAR_mm10_v2_7"
  # gtf file with transcripts
  annotation: "/hpcnfs/data/DP/Databases/STAR_mm10_v2_7/gencode.vM19.primary_assembly.annotation.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  pvalue: 0.05
  log2fc: 2
  # contrasts for the deseq2 results method
  contrasts:
    P1KO-vs-WT:
      - P1KO
      - WT

params:
  star: "--outSAMtype BAM SortedByCoordinate \
        --outSAMattributes Standard \
        --outFilterMultimapNmax 1 \
        --bamRemoveDuplicatesType UniqueIdentical"
  featureCounts: "-s 0 -t exon -g gene_name"
  fastp-se: "--stdin -t 1 -A -Q -L"
  fastp-pe: "-t 1 -A -Q -L"